# Generated by Django 4.2.3 on 2023-07-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_subcategoria_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
